flaskapp/order/models.py
#!/usr/bin/python
# -*- coding:utf8 -*-
import os

from flask import request
from flaskapp.extensions import db
from sqlalchemy import or_
from jieba.analyse.analyzer import ChineseAnalyzer


class Basic_info(db.Model):
    __tablename__ = 'basic_info'

    id = db.Column(db.INTEGER, primary_key=True)
    avator = db.Column(db.TEXT)
    name = db.Column(db.TEXT)
    college = db.Column(db.TEXT)
    institute = db.Column(db.TEXT)
    tel = db.Column(db.TEXT)
    email = db.Column(db.TEXT)
    C = db.Column(db.INT)
    J = db.Column(db.INT)
    Q = db.Column(db.INT)

    def __repr__(self):
        return 'info:{},{}'.format(self.id, self.name)

    @staticmethod
    def get_basic_info(id, path):
        info = Basic_info.query.filter_by(id=id).first()

        college = info.college
        name = info.name
        avator = Avator.get_avator(id, path)
        institute = info.institute
        tel = info.tel
        email = info.email
        c = info.C
        j = info.J
        q = info.Q
        C = '长江学者' if c else ''
        J = '杰出青年' if j else ''
        Q = '千人计划' if q else ''
        return name, college, avator, institute, tel, email, C, J, Q

    def search_box(self, name):
        """
        根据搜索框对专家的模糊搜索
        :param name: 搜索框中输入的不完全专家名称
        :return: 通过模糊搜索之后得到结果的陈列
        """
        info = Basic_info.query.filter(or_(Basic_info.name.like('%' + name + '%')))
        return info

    # 返回对应id专家的详细信息
    # def get_basic_info(id):
    #     info = basic_info.query.filter_by(id=id).first()
    #
    #     college = info.college
    #     name = info.name
    #     institute = info.institute
    #     tel = info.tel
    #     email = info.email
    #     c = info.C
    #     j = info.J
    #     q = info.Q
    #     C = '长江学者' if c else ''
    #     J = '杰出青年' if j else ''
    #     Q = '千人计划' if q else ''
    #
    #     return college, name, institute, tel, email, C, J, Q

    @staticmethod
    # 返回id编号从a到b专家的查询结果，可以直接调用pignate
    def get_many(a, b):
        """
        获得编号从a到b的专家的基本信息
        :param a:
        :param b:
        :return:
        """
        # 查询专家基本信息的表
        info = Basic_info.query.filter(Basic_info.id >= a, Basic_info.id <= b)
        return info


class Avator(db.Model):
    __tablename__ = 'avator'

    id = db.Column(db.INTEGER, primary_key=True)
    img = db.Column(db.BLOB)

    def __repr__(self):
        return 'info_img:{}'.format(self.id)

    @staticmethod
    # 根据id获取头像信息
    def get_avator(id, path):
        """
        根据id来获取对应专家的头像
        当数据据和缓存都没有时候，默认给一个空白头像
        :param id:  专家的id
        :param path: 存放头像缓存的路径,默认路径为'path/interface/avator'
        :return: 返回头像的对应的路径
        """

        # 为头像缓存添加路径
        if not os.path.exists(path):
            os.mkdir(path)

        # 调用时返回的是调用函数的路径
        # root = os.getcwd()
        # print 'root', root
        # 头像缓存在get_avator中，如果存在就无需从数据库中获取了（以id.jpg的方式缓存）
        img_name = str(id) + '.jpg'
        avator_path = os.path.join(path, img_name)
        # print 'avator_path', avator_path

        if os.path.exists(avator_path):
            print img_name + ' is existed'
            return img_name
        # 缓存中没有，从数据库中获取
        else:
            try:
                img = Avator.query.filter_by(id=id).first().img
                avator = open(avator_path, 'wb')
                avator.write(img)
                avator.close()
                print 'get avator: ', img_name
                return img_name

            except:
                print 'cant find avator, plz give a blank one'
                return 'blank.jpg'

    @staticmethod
    def init_avator():
        info = Basic_info.query.filter(Basic_info.id >= 0).all()
        for data in info:
            Avator.get_avator(data.id, 'flaskapp/static/order/avator/')


class Details(db.Model):
    __tablename__ = 'details'

    id = db.Column(db.INTEGER, primary_key=True)
    name = db.Column(db.TEXT)
    college = db.Column(db.TEXT)
    career = db.Column(db.TEXT)
    contribute = db.Column(db.TEXT)
    job = db.Column(db.TEXT)

    @staticmethod
    def get_details(id):
        try:
            pro = Details.query.filter_by(id=id).first()
            career = pro.career.split('。')
            contribute = pro.contribute.split('。')
            job = pro.job.split('。')
            return career, contribute, job
        except Exception as e:
            print e


class pro_art(db.Model):
    __tablename__ = 'pro_art'

    id = db.Column(db.INTEGER, primary_key=True)
    name = db.Column(db.TEXT)
    article_list = db.Column(db.TEXT)

    @staticmethod
    def get_article_list(id):
        """
        返回专家对应的所有论文的列表
        :param id:
        :return:
        """
        info = pro_art.query.filter_by(id=id).first()
        art_contents = []

        list_str = info.article_list.strip()
        if list_str:
            lists = list_str.split(',')
            for list in lists:
                if list:
                    art_contents.append(articles.give_article(list))

        # for content in art_contents:
        #     print content

        return art_contents


class articles(db.Model):
    __tablename__ = 'articles'

    id = db.Column(db.INTEGER, primary_key=True)

    title = db.Column(db.TEXT)
    key_word = db.Column(db.TEXT)
    abstract = db.Column(db.TEXT)
    author = db.Column(db.TEXT)
    journal = db.Column(db.TEXT)

    @staticmethod
    def get_article(id):
        info = articles.query.filter_by(id=id).first()

        title = info.title
        key_word = info.key_word
        abstract = info.abstract
        author = info.author
        journal = info.journal

        return title, key_word, abstract, author, journal

    @staticmethod
    def give_article(id):
        """
        给出一个论文的字符串数据
        :param id:
        :return:
        """
        title, key_word, abstract, author, journal = articles.get_article(id)

        return title + '. ' + author + '. ' + journal


class Professor():
    """
    返回专家的信息
    get_many(a , b, path): 返回 id（a~b）之间的专家基本数据(query对象，可以接pagenate)
    init(id, path): 返回对应id专家的所有信息
    """

    def __init__(self, id, path):
        self.id = id
        self.career, self.contribute, self.job = Details.get_details(id)
        self.name, self.college, self.avator, self.institute, self.tel, self.email, self.C, self.J, self.Q = Basic_info.get_basic_info(
            id, path)
        self.art_contents = pro_art.get_article_list(id)


class Lab_Form(db.Model):
    __tablename__ = 'info_lab'
    __analyzer__ = ChineseAnalyzer()

    id = db.Column(db.INTEGER, primary_key=True)
    lab_name = db.Column(db.TEXT)
    lab_school = db.Column(db.TEXT)
    lab_introduction = db.Column(db.TEXT)
    lab_location = db.Column(db.TEXT)
    lab_postcode = db.Column(db.TEXT)
    lab_supportunit = db.Column(db.TEXT)
    lab_tel = db.Column(db.TEXT)
    lab_fax = db.Column(db.TEXT)
    lab_mail = db.Column(db.TEXT)
    lab_url = db.Column(db.TEXT)
    lab_director = db.Column(db.TEXT)
    lab_contactor = db.Column(db.TEXT)

    def __repr__(self):
        return '<Lab_Form {}'.format(self.lab_name, self.lab_school, self.lab_introduction,
                                     self.lab_location, self.lab_postcode, self.lab_supportunit,
                                     self.lab_director, self.lab_contactor)

    def get_info(self, name):
        """
        根据名称查询数据库
        :param name: 实验室名称
        :return: 实验室基本信息
        """
        info = Lab_Form.query.filter_by(lab_name=name).first()
        return info

    def select_info(self):
        """
        获取第page页数据
        :param page: 页数
        :return: 分页后的数据
        """
        try:
            info = Lab_Form.query
            return info
        except IOError:
            return None

    def search_box(self, name):
        """
        根据搜索框对实验室模糊搜索
        :param name: 搜索框中输入的不完全实验室名称
        :return: 通过模糊搜索之后得到结果的陈列
        """
        info = Lab_Form.query.filter(or_(Lab_Form.lab_name.like('%' + name + '%')))
        return info

flaskapp/order/__init__.py
# -*- coding: utf-8 -*-
"""The public module, including the homepage and user auth."""

from . import views  # noqa

flaskapp/order/views.py
#!/usr/bin/python
# -*- coding:utf8 -*-
from flask import render_template, Blueprint
from flask_login import login_required
from models import *

blueprint = Blueprint('order', __name__, static_folder='../static/order')


@blueprint.route('/searchbox1/<int:page>')
@login_required
def searchbox1(page):
    """
    用户自定义搜索，根据专家名称进行模糊搜索
    :return: 专家搜索结果的陈列页面
    """
    basic_info = Basic_info()

    # 初次运行网站时执行，获得专家图片缓存（路径：'flaskapp/static/order/avator/'）
    # Avator.init_avator()

    expert_name = request.values.get('condition1')
    if not expert_name:
        expert_name = ""
    pagination = basic_info.search_box(expert_name).paginate(page=page, per_page=6, error_out=False)
    return render_template('order/index.html', title='三螺旋', expert_name=expert_name, pagination=pagination)

# @blueprint.route('/order_confirm')
# @login_required
# def about():
#     """
#         路由：order_confirm.html
#         跳转订单确认页面
#     """
#     return render_template('order/order_confirm.html')


# @blueprint.route('/order_list')
# @login_required
# def order():
#     """
#         路由：order_list.html
#         跳转订单列表页面
#     """
#     return render_template('order/order_list.html')


# @blueprint.route('/<string:con>/<int:page>')
# @login_required
# def add(con, page):
#     """
#         路由：add.html
#         按地址或公司名查询
#         返回结果在add.html中显示
#     """
#     # pagination = search_engine(area, page)
#     pagination = select_paginate_by_add(con, page)
#     return render_template('order/add.html', title="三螺旋", pagination=pagination, name=con)


# @blueprint.route('/demand')
# @login_required
# def demand():
#     """
#         路由：
#         触发搜索
#         返回add方法
#     """
#     content = request.args.get('requirement')
#     return add(content, 1)

@blueprint.route('/profile/<int:id>')
@login_required
def profile(id):
    info = Professor(id, 'avator/')
    return render_template('order/profile.html', title="三螺旋", info=info)


@blueprint.route('/searchbox2/<int:page>')
@login_required
def searchbox2(page):
    """
    用户自定义搜索，根据重点实验室名称进行模糊搜索
    :return: 实验室陈列页面
    """
    lab_info = Lab_Form()
    lab_name = request.values.get('condition2')
    if not lab_name:
        lab_name = ""
    pagination = lab_info.search_box(lab_name).paginate(page=page, per_page=6, error_out=False)
    return render_template('laboratory/lab_search.html', title='三螺旋', lab_name = lab_name, pagination=pagination)

@blueprint.route('/lab_infoshow/<string:name>')
def lab_infoshow(name):
    labform = Lab_Form()
    info = labform.get_info(name=name)
    return render_template('laboratory/lab_infoshow.html', title="三螺旋", info=info)

flaskapp/templates/order/add.html
   {% extends "order/base.html" %}
{% block content %}
    {{ super() }}
    <nav class="pagination-bottom" style="text-align: center">
          <ul class="pagination">
                <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
                    <a href="{% if pagination.has_prev %}{{ url_for('order.add',con=name ,page=pagination.prev_num) }}{% else %}#{% endif %}">
                        «
                    </a>
                </li>
                {% for p in pagination.iter_pages() %}
                    {% if p %}
                        {% if p == pagination.page %}
                        <li class="active">
                            <a href="{{ url_for('order.add',con=name, page = p) }}">{{ p }}</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{{ url_for('order.add',con=name, page = p) }}">{{ p }}</a>
                        </li>
                        {% endif %}
                    {% else %}
                    <li class="disabled"><a href="#">…</a></li>
                    {% endif %}
                {% endfor %}
                <li{% if not pagination.has_next %} class="disabled"{% endif %}>
                    <a href="{% if pagination.has_next %}{{ url_for('order.add',con=name,page=pagination.next_num) }}{% else %}#{% endif %}">
                    »
                    </a>
                </li>
          </ul>
        </nav>
{% endblock %}

flaskapp/templates/order/base.html
{% extends "bootstrap/base.html" %}
{% block title %}三螺旋大数据{% endblock %}
{% block head %}
{{ super() }}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

<link rel="shortcut icon" href="../static/order/favicon.ico" type="image/x-icon">
<link rel="icon" href="../static/order/favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="../static/order/css/custom.css">
<!--<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('public.home') }}">三螺旋</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('order.searchbox1',page=1 ) }}">主页</a></li>
{#                <!--<li><a href="{{ url_for('order.order') }}">订单列表</a></li>-->#}
{#                <!--<li><a href="{{ url_for('order.about') }}">确认订单</a></li>-->#}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    {{ super() }}
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="../static/order/js/script.js"></script>
{% endblock %}

flaskapp/templates/order/index.html
{% extends "order/base.html" %}
{% block title %}三螺旋大数据{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block navbar %}
    {{ super() }}
{% endblock %}
{% block content %}
{#    {{ super() }}#}
    <div class="container">
         <div class="row clearfix">
		<div class="col-md-12 column">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                         <span class="sr-only">Toggle navigation</span>
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span></button>
                    <a class="navbar-brand" href="/searchbox1/1">专家</a>
				</div>

                <div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                         <span class="sr-only">Toggle navigation</span>
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span></button>
                    <a class="navbar-brand" href="/searchbox2/1">实验室</a>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<form class="navbar-form navbar-left" role="search" action="/searchbox1/1">
						<div class="form-group">
							<input type="text" class="form-control" name="condition1" placeholder="请输入专家名称">
						</div>
                        <button type="submit" class="btn btn-default">检索</button>
					</form>
				</div>
			</nav>
		</div>
	</div>

    <div class="row">

            {% for f in pagination.items %}
            {% if f.id!="" %}
            <!--<div class="col-sm-2">111111</div>-->
            <div class="col-sm-12 panel panel-default">

                <div class="col-sm-2" style="text-align:center;width: 160px;height: 150px;margin-top: 10px"><img src="../../static/order/avator/{{ f.avator}}" width="100%" height="100%"></div>

                <div class="col-sm-10">
                    <h3><a href="{{ url_for('order.profile',id=f.id) }}" target="_blank">{{ f.name }}</a></h3>

                    <div class="user-info-article">
                        <span>学校:    {{ f.college }}</span>
                    </div>
                    <div class="user-info-subject">
                        <span>学院:    {{ f.institute }}</span>
                    </div>
                    <div class="user-info-subject">
                        <span>邮箱:    {{ f.email }}</span>
                    </div>
                    <div class="user-info-subject">
                        <span>联系电话:{{ f.tel }}</span>
                    </div>
                </div>

            </div>
            {% endif %}
            {% endfor %}
        </div>

    <div class="row-space"></div>

        <nav class="pagination-bottom" style="text-align: center">
          <ul class="pagination">
                <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
                    <a href="{% if pagination.has_prev %}{{ url_for('order.searchbox1', condition1=expert_name, page=pagination.prev_num) }}{% else %}#{% endif %}">
                        «
                    </a>
                </li>
                {% for p in pagination.iter_pages() %}
                    {% if p %}
                        {% if p == pagination.page %}
                        <li class="active">
                            <a href="{{ url_for('order.searchbox1', condition1=expert_name, page = p) }}">{{ p }}</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{{ url_for('order.searchbox1', condition1=expert_name, page = p) }}">{{ p }}</a>
                        </li>
                        {% endif %}
                    {% else %}
                    <li class="disabled"><a href="#">…</a></li>
                    {% endif %}
                {% endfor %}
                <li{% if not pagination.has_next %} class="disabled"{% endif %}>
                    <a href="{% if pagination.has_next %}{{ url_for('order.searchbox1', condition1=expert_name, page=pagination.next_num) }}{% else %}#{% endif %}">
                    »
                    </a>
                </li>
            </ul>
        </nav>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="../static/order/js/script.js"></script>
{% endblock %}


flaskapp/templates/order/order_confirm.html
{% extends "order/base.html" %}

{% block content %}
    <div class="container">
        <div class="row page-header">
            <h1>确认订单</h1>
        </div>

        <div class="row">
            <label class="order-info-label">订单号：1</label>
        </div>
        <div class="row order-info-item">
            <div class="col-md-5 col-sm-5 col-xs-5 order-info-detail">
                <div>
                    <span>薛建阳</span>
                </div>
                <div>
                    <span>西安建筑科技大学</span>
                </div>
                <div>
                    <span>土木工程</span>
                </div>
            </div>
            <div class="col-md-5 col-sm-5 col-xs-5 order-info-cost">
                <div>
                    <span>联系费用：</span><span>1000</span>
                </div>
                <div>
                    <span>优惠券：</span><span>1000</span>
                </div>
                <div>
                    <span>合计费用：</span><span>0</span>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 order-info-operate">
                <input class="btn btn-default" type="button" name="delete-order" value="移除">
            </div>
        </div>
        <div class="row-space"></div>

        <div class="row">
            <label class="order-info-label">订单号：2</label>
        </div>
        <div class="row order-info-item">
            <div class="col-md-5 col-sm-5 col-xs-5 order-info-detail">
                <div>
                    <span>陈志华</span>
                </div>
                <div>
                    <span>天津大学</span>
                </div>
                <div>
                    <span>土木工程</span>
                </div>
            </div>
            <div class="col-md-5 col-sm-5 col-xs-5 order-info-cost">
                <div>
                    <span>联系费用：</span><span>1000</span>
                </div>
                <div>
                    <span>优惠券：</span><span>1000</span>
                </div>
                <div>
                    <span>合计费用：</span><span>0</span>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 order-info-operate">
                <input class="btn btn-default" type="button" name="delete-order" value="移除">
            </div>
        </div>
        <div class="row-space"></div>

        <div class="row">
            <label class="order-info-label">订单号：3</label>
        </div>
        <div class="row order-info-item">
            <div class="col-md-5 col-sm-5 col-xs-5 order-info-detail">
                <div>
                    <span>张根保</span>
                </div>
                <div>
                    <span>重庆大学</span>
                </div>
                <div>
                    <span>机械工程</span>
                </div>
            </div>
            <div class="col-md-5 col-sm-5 col-xs-5 order-info-cost">
                <div>
                    <span>联系费用：</span><span>1000</span>
                </div>
                <div>
                    <span>优惠券：</span><span>1000</span>
                </div>
                <div>
                    <span>合计费用：</span><span>0</span>
                </div>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 order-info-operate">
                <input class="btn btn-default" type="button" name="delete-order" value="移除">
            </div>
        </div>
        <div class="row-space"></div>

        <div class="row text-right">
            <label for="">总计费用：0</label>
        </div>
        <div class="row-space"></div>

        <div class="row text-right">
            <input class="btn btn-default" id="submit-user" name="submit-user" type="submit" value="提交订单并支付">
        </div>
        <div class="row-space"></div>
    </div>
{% endblock %}

flaskapp/templates/order/order_list.html

{% extends "order/base.html" %}


{% block content %}
    <div class="container">
        <div class="row page-header">
            <h1>订单列表</h1>
        </div>

        <table class="table table-hover table-order-list">
            <thead>
                <tr>
                    <th>编号</th>
                    <th>需求</th>
                    <th>专家</th>
                    <th>学校</th>
                    <th>专业</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td></td>
                    <td>薛建阳</td>
                    <td>西安建筑科技大学</td>
                    <td>土木工程</td>
                    <td>正在联系专家</td>
                    <td>
                        <input class="btn btn-default" type="button" name="" value="详情">
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td></td>
                    <td>陈志华</td>
                    <td>天津大学</td>
                    <td>土木工程</td>
                    <td>专家已同意</td>
                    <td>
                        <input class="btn btn-default" type="button" name="" value="详情">
                    </td>
                </tr>
                <tr>
                    <td>3</td>
                    <td></td>
                    <td>张根保</td>
                    <td>重庆大学</td>
                    <td>机械工程</td>
                    <td>专家已拒绝</td>
                    <td>
                        <input class="btn btn-default" type="button" name="" value="详情">
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}
