flaskapp/order/views.py
#!/usr/bin/python
# -*- coding:utf8 -*-
from flask import render_template, Blueprint
from flask_login import login_required
from models import *

blueprint = Blueprint('order', __name__, static_folder='../static/order')


@blueprint.route('/searchbox1/<int:page>')
@login_required
def searchbox1(page):
    """
    用户自定义搜索，根据专家名称进行模糊搜索
    :return: 专家搜索结果的陈列页面
    """
    basic_info = Basic_info()

    # 初次运行网站时执行，获得专家图片缓存（路径：'flaskapp/static/order/avator/'）
    # Avator.init_avator()

    expert_name = request.values.get('condition1')
    if not expert_name:
        expert_name = ""
    pagination = basic_info.search_box(expert_name).paginate(page=page, per_page=6, error_out=False)
    return render_template('order/index.html', title='三螺旋', expert_name=expert_name, pagination=pagination)

# @blueprint.route('/order_confirm')
# @login_required
# def about():
#     """
#         路由：order_confirm.html
#         跳转订单确认页面
#     """
#     return render_template('order/order_confirm.html')


# @blueprint.route('/order_list')
# @login_required
# def order():
#     """
#         路由：order_list.html
#         跳转订单列表页面
#     """
#     return render_template('order/order_list.html')


# @blueprint.route('/<string:con>/<int:page>')
# @login_required
# def add(con, page):
#     """
#         路由：add.html
#         按地址或公司名查询
#         返回结果在add.html中显示
#     """
#     # pagination = search_engine(area, page)
#     pagination = select_paginate_by_add(con, page)
#     return render_template('order/add.html', title="三螺旋", pagination=pagination, name=con)


# @blueprint.route('/demand')
# @login_required
# def demand():
#     """
#         路由：
#         触发搜索
#         返回add方法
#     """
#     content = request.args.get('requirement')
#     return add(content, 1)

@blueprint.route('/profile/<int:id>')
@login_required
def profile(id):
    info = Professor(id, 'avator/')
    return render_template('order/profile.html', title="三螺旋", info=info)


@blueprint.route('/searchbox2/<int:page>')
@login_required
def searchbox2(page):
    """
    用户自定义搜索，根据重点实验室名称进行模糊搜索
    :return: 实验室陈列页面
    """
    lab_info = Lab_Form()
    lab_name = request.values.get('condition2')
    if not lab_name:
        lab_name = ""
    pagination = lab_info.search_box(lab_name).paginate(page=page, per_page=6, error_out=False)
    return render_template('laboratory/lab_search.html', title='三螺旋', lab_name = lab_name, pagination=pagination)

@blueprint.route('/lab_infoshow/<string:name>')
def lab_infoshow(name):
    labform = Lab_Form()
    info = labform.get_info(name=name)
    return render_template('laboratory/lab_infoshow.html', title="三螺旋", info=info)

flaskapp/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

flaskapp/templates/401.html
 {% extends "layout.html" %} {% block page_title %}Unauthorized{% endblock %} {% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>您没有权限访问该页面，请 <a href="{{ url_for('public.login')}}">登录</a> 或
            <a href="{{ url_for('public.register') }}">注册新用户</a>.
        </p>
    </div>
</div>
{% endblock %}

flaskapp/templates/footer.html
<footer>
    <small>
        <ul class="company">
            <li>© 三螺旋大数据科技（昆山）有限公司</li>
        </ul>
        <ul class="ghs">
            <span>备案号：</span>
            <a target="_blank" href="http://www.miitbeian.gov.cn">
                <span>苏ICP备17021343号-1</span>
            </a>
        </ul>
        <ul class="footer-nav">
            <li><a href="{{ url_for('public.about') }}">关于我们</a></li>
            <li><a href="mailto:sanluoxuan@qq.com">联系我们</a></li>
        </ul>
    </small>
</footer>

flaskapp/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>{% block page_title %}
        三螺旋
        {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}{% endblock %}">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
    {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container-fluid{% endblock content_class %}">

    <div role="main">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
            <div class="col-md-12">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                    {{message}}
                </div><!-- end .alert -->
                {% endfor %}
            </div><!-- end col-md -->
        </div><!-- end row -->
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>


flaskapp/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('public.home') }}">
                三螺旋
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('order.searchbox1',page=1 )}}">主页</a></li>
                <li><a href="{{ url_for('public.about') }}">关于</a></li>
            </ul>
            {% if current_user and current_user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <p class="navbar-text"><a class="navbar-link"
                                                  href="{{ url_for('user.members') }}">欢迎： {{ current_user.username }}</a>
                        </p>
                    </li>
                     <li><p class="navbar-text"><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i>注销</a></p></li>
                    </li>

                </ul>
            {% elif form %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('public.register') }}">注册</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('public.login') }}">登录</a></li>
                </ul>

            {% endif %}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>
